# -*- coding: utf-8 -*-
"""stick_game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dh4Hm5vhAa0Etm3NWVogKGn7-BSsG_tK
"""

n = int(input("How many sticks in the pile"))
#ask the number of sticks in the pile
print("There are", n, "sticks in the pile")
#print the number of sticks
name = input("What is your name")
#ask a user for his/her name
sticks = int(input("How many sticks you will take (1 or 2)"))
#ask a user how many sticks he/she want to take out
count = 0
#set the initial attempt as zero
while n != 0:
#set while loop to continue to take sticks out until no sticks left
    if sticks > 2:
      print("No, you cannot take more than 2 sticks")
      #check that a user cannot take more than 2 sticks
    elif sticks < 1:
      print("No, you cannot take less than 1 sticks")
      #check that a user cannot take less than 1 sticks
    elif sticks > n:
      print("There are not enough sticks to take")
      #check that there is not enough sticks to take
    else:
      n = n - sticks
      #subtract sticks
      count = count + 1
      #update count
      if n == 0:
          print("OK There is no stick left in the pile. You spent", count, "times")
          #game ends if there is no sticks left. Display the number of attempts used
          break
          #exit the loop
      else:
          print("There are", n, "sticks in the pile")
          #if there is sticks remaining, continue the game and show the number of sticks left
    sticks = int(input(name + ", How many sticks you will take (1 or 2)"))
    #continue to ask for the number of sticks a user want to take out